// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokeTCGWebAPI.Models;

namespace PokeTCGWebAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190627152742_Cards")]
    partial class Cards
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("PokeTCGWebAPI.Models.Card", b =>
                {
                    b.Property<int>("CardID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CardName");

                    b.Property<int?>("SetID");

                    b.HasKey("CardID");

                    b.HasIndex("SetID");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("PokeTCGWebAPI.Models.CardType", b =>
                {
                    b.Property<int>("CardTypeID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CardTypeName");

                    b.Property<DateTime>("LastUpdateDate");

                    b.HasKey("CardTypeID");

                    b.ToTable("CardTypes");
                });

            modelBuilder.Entity("PokeTCGWebAPI.Models.Set", b =>
                {
                    b.Property<int>("SetID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("SetCode");

                    b.Property<bool>("SetExpanded");

                    b.Property<string>("SetLogoURL");

                    b.Property<string>("SetName");

                    b.Property<DateTime>("SetReleaseDate");

                    b.Property<string>("SetSeries");

                    b.Property<bool>("SetStandard");

                    b.Property<string>("SetSymbolURL");

                    b.HasKey("SetID");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("PokeTCGWebAPI.Models.Card", b =>
                {
                    b.HasOne("PokeTCGWebAPI.Models.Set", "Set")
                        .WithMany("Cards")
                        .HasForeignKey("SetID");
                });
#pragma warning restore 612, 618
        }
    }
}
